<?php 
$form=$this->form;
$form->prepare();
$form->setAttribute('action', $this->url('news/article/add-cate-article'));
?>
<div class="row-fluid">		
	<div class="col-md-2">
		<div class="list-group">
		  <a href="<?=$this->url('news/article/add-cate-article') ?>" class="list-group-item">Quản lý danh mục </a>		  		 		 
		</div>
	</div>
	<div class="col-md-10">	
	<?php echo $this->form()->openTag($form)?>
		<div class="row">					
			<div class="col-md-3">  
			<div class="input-group input-group-edit">			
				<span class="input-group-addon">Chọn cấp danh mục:</span>									
				 <?php echo $this->formRow($form->get('parent_id'));?>												
			</div>		
			</div>
		</div>
		<div class="row">
			<div class="col-md-7">  			
					<div class="input-group input-group-edit">
				  		<span class="input-group-addon">Danh mục</span>
				  		<?php echo $this->formRow($form->get('title'));?>	
				  	</div>
					<div class="input-group input-group-edit">
				  		<span class="input-group-addon">Alias</span>
				  		<?php echo $this->formRow($form->get('alias'));?>	
				  	</div>				  	
				  				  	
				 <div class="pull-right">
					  	<div class="btn-group">  	
					  	<button type="submit" class="btn btn-default" name="add-book" id="add-book" value="add-book">Lưu</button>
					  	<button type="button" class="btn btn-default" name="delete" value="delete">Xóa</button>		  	
					  </div>    
					</div>
			
			</div>				
		</div>
		<?php echo $this->form()->closeTag($form);?>
		<div class="row">
		<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>Tên</th>
						<th>Alias</th>
						<th>Path</th>
						<th>Tool</th>
					</tr>
				</thead>
				<tbody>
			<?php foreach ($cate as $cate):?>
				<tr>
						<td><?=$cate->id ?></td>
						<td><?=$this->custom_helper()->add_prefixCate($cate->path).$cate->title ?></td>
						<td><?=$cate->alias ?></td>
						<td><?=$cate->path ?></td>						
						<td>
						<div class="btn-group btn-group-sm" role="group" aria-label="...">
						<a href='<?=$this->url('news/article/edit-cate-article')."/".$cate->id ?>' class="btn btn-default"  data-toggle='tooltip' data-placement='top' title='Sửa danh mục'><i class="fa fa-pencil-square-o"></i></a> 
						<a href='<?=$this->url('news/article/delete-cate-article')."/".$cate->id ?>' class="btn btn-default" data-toggle='tooltip' data-placement='top' title='Xóa danh mục' > <i class="fa fa-times"></i></a>
						</div>
						</td>
					</tr>
				<?php endforeach;?>				
			</tbody>
			</table>
		</div>
					
	</div>
</div>

