<script>
	$(document).ready(function(){
			
			$('.but1').click(function(){
				$('#targetElement').addClass('change-effect');
			}); 
			 $('.but2').click(function(){
				$('#targetElement').removeClass('change-effect');
				}); 
			$( ".but2x" ).click(function() {
				  $( "#targetElement" ).animate({
				    opacity: 0,
				    
				  }, 1000, function() {
				    // Animation complete.
				  });
				});
		});
	
</script>
<!-- the component -->
<div class="row">
	<div class="col-md-12 ">
		<div style="width: 300px;height: 300px;background: green;" id="targetElement" >				
			<!-- TEST LOADER SPIN -->		
		</div>
		<button class="but1">add</button>
		<button class="but2">remove</button>

	</div>
</div>

